name: Docker Image CI

on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ifurther/geant4:base
