name: Docker Image CI

on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:

  build:

    runs-on: ubuntu-latest
    permission: 
      packages: wirte
      contents: read
    steps:
      - name: Checkout out the repo
        uses: actions/checkout@v2
      - name: Log in the ghc registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ifurther/geant4:base

